server:
  port: 8000
spring:
  application:
    name: cloud-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  zipkin:                             # 需要开启zipkin服务
    base-url: http://localhost:9411
    discovery-client-enabled: false   # 关闭服务发现，否则Spring Cloud会把zipkin的url当做服务名称
    sender:
      type: web # 设置使用http的方式传输数据
  sleuth:
    sampler:
      probability: 1.0 # spring.sleuth.sampler.probability=1.0表示以 100% 的概率将链路的数据上传给 Zipkin Server ， 在默认情况下 ， 该值为0.1
    web:
      client:
        enabled: true
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/suphowe?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml